name: MusicVideoGenerator

options:
  bundleIdPrefix: com.musicvideogenerator
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  developmentLanguage: en

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  MusicVideoGenerator:
    type: application
    platform: iOS
    sources:
      - MusicVideoGenerator
    settings:
      base:
        INFOPLIST_FILE: MusicVideoGenerator/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.musicvideogenerator.app
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        ENABLE_BITCODE: NO
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
      configs:
        debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"

    info:
      path: MusicVideoGenerator/Info.plist
      properties:
        CFBundleDisplayName: MusicVideo Generator
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "We need access to analyze audio files"
        NSPhotoLibraryUsageDescription: "We need access to save your generated music videos"
        NSPhotoLibraryAddUsageDescription: "We need access to save your generated music videos"
        NSSpeechRecognitionUsageDescription: "We need access to transcribe lyrics from your audio files"

schemes:
  MusicVideoGenerator:
    build:
      targets:
        MusicVideoGenerator: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
